groups:
- name: all
  jobs:
  - upload-osba
  - configure-osba
  - deploy-osba
  - delete-osba

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: azure-tile-pipelines
  type: git
  source:
    uri: https://github.com/CloudFoundryOnAzure/azure-tile-pipelines
    branch: master

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/CloudFoundryOnAzure/pcf-pipelines
    branch: master

- name: pivnet-osba
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pivnet_token}}
    product_slug: azure-open-service-broker-pcf
    product_version: {{osba_major_minor_version}}
    sort_by: semver

jobs:
- name: upload-osba
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      resource: pivnet-osba
      trigger: true
      params:
        globs:
        - "azure-open-service-broker*.pivotal"

  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      IAAS: "azure"
      NO_PROXY: ""
      OM_IP: ""

  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}

- name: configure-osba
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: azure-tile-pipelines
    - get: pcf-pipelines
      passed: [upload-osba]
      trigger: true

  - task: prepare-config
    file: azure-tile-pipelines/open-service-broker-azure/tasks/prepare-config/task.yml
    params:
      AZURE_ENVIRONMENT:           {{azure_environment}}
      AZURE_TENANT_ID:             {{azure_tenant_id}}
      AZURE_SUBSCRIPTION_ID:       {{azure_subscription_id}}
      AZURE_CLIENT_ID:             {{azure_client_id}}
      AZURE_CLIENT_SECRET:         {{azure_client_secret}}
      ASYNC_REDIS_DB:              {{async_redis_db}}
      ASYNC_REDIS_ENABLE_TLS:      {{async_redis_enable_tls}}
      ASYNC_REDIS_HOST:            {{async_redis_host}}
      ASYNC_REDIS_PASSWORD:        {{async_redis_password}}
      ASYNC_REDIS_PORT:            {{async_redis_port}}
      STORAGE_REDIS_DB:            {{storage_redis_db}}
      STORAGE_REDIS_ENABLE_TLS:    {{storage_redis_enable_tls}}
      STORAGE_REDIS_HOST:          {{storage_redis_host}}
      STORAGE_REDIS_PASSWORD:      {{storage_redis_password}}
      STORAGE_REDIS_PORT:          {{storage_redis_port}}
      LOG_LEVEL:                   {{log_level}}
      MIN_STABILITY:               {{min_stability}}
      CRYPTO_AES256_KEY:           {{crypto_aes256_key}}
      NETWORK:                     {{network}}
      SINGLETON_AVAILABILITY_ZONE: {{singleton_availability_zone}}
      OTHER_AVAILABILITY_ZONE:     {{other_availability_zone}}

  - task: configure-osba
    file: azure-tile-pipelines/tasks/config-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}

- name: deploy-osba
  serial: true
  max_in_flight: 1
  serial_groups: [full]

  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [configure-osba]
      trigger: true

  - task: deploy-osba
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      PRODUCT_NAME: azure-open-service-broker-pcf

- name: delete-osba
  serial: true
  max_in_flight: 1
  serial_groups: [full]

  plan:
  - aggregate:
    - get: azure-tile-pipelines
    - get: pcf-pipelines
      passed: [deploy-osba]
      trigger: true

  - task: unstage-osba
    file: azure-tile-pipelines/tasks/unstage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PRODUCT_NAME: azure-open-service-broker-pcf

  - task: delete-osba
    file: azure-tile-pipelines/tasks/delete-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PRODUCT_NAME: azure-open-service-broker-pcf
      PRODUCT_VERSION: 0.12.0
